# Generated by Django 5.2.8 on 2025-11-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('tipo', models.CharField(help_text='Ej: textil, cerámica, 3D, etc.', max_length=100, verbose_name='Tipo')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0, verbose_name='Cantidad disponible')),
                ('unidad', models.CharField(blank=True, help_text='Ej: unidades, metros, kg (opcional)', max_length=50, verbose_name='Unidad')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('cliente_telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('cliente_red_social', models.CharField(blank=True, help_text='Opcional: @usuario de Instagram, Facebook, etc.', max_length=150, verbose_name='Usuario/red social')),
                ('descripcion', models.TextField(verbose_name='Descripción de lo solicitado')),
                ('fecha_solicitada', models.DateField(blank=True, help_text='Fecha en que necesita el producto (opcional)', null=True, verbose_name='Fecha requerida')),
                ('plataforma_origen', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('presencial', 'Presencial'), ('sitio_web', 'Sitio web'), ('otro', 'Otra plataforma')], default='sitio_web', max_length=20, verbose_name='Plataforma de origen')),
                ('plataforma_otro', models.CharField(blank=True, help_text="Especificar si eliges 'Otra plataforma'", max_length=100, verbose_name='Otra plataforma')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('en_proceso', 'En proceso'), ('realizada', 'Realizada'), ('entregada', 'Entregada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='solicitado', max_length=20, verbose_name='Estado del pedido')),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20, verbose_name='Estado de pago')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total del pedido')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto pagado')),
                ('token_seguimiento', models.CharField(blank=True, default='', editable=False, max_length=20, unique=True, verbose_name='Token de seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PedidoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pedidos/', verbose_name='Imagen de referencia')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mainApp.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Imagen de pedido',
                'verbose_name_plural': 'Imágenes de pedido',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 1')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 2')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 3')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='mainApp.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='mainApp.producto', verbose_name='Producto de referencia'),
        ),
    ]
