# Generated by Django 5.2.8 on 2025-11-21 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedidoimagen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(help_text='Ej: textil, cerámica, 3D, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(blank=True, help_text='Ej: unidades, metros, kg', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_red_social',
            field=models.CharField(blank=True, help_text='Opcional: @usuario de Instagram, Facebook, etc.', max_length=150),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('en_proceso', 'En proceso'), ('realizada', 'Realizada'), ('entregada', 'Entregada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='solicitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_solicitada',
            field=models.DateField(blank=True, help_text='Fecha en que necesita el producto', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plataforma_origen',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('presencial', 'Presencial'), ('sitio_web', 'Sitio web'), ('otro', 'Otra plataforma')], default='sitio_web', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plataforma_otro',
            field=models.CharField(blank=True, help_text='Especificar', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='token_seguimiento',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidoimagen',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidoimagen',
            name='imagen',
            field=models.ImageField(upload_to='pedidos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
