# Generated by Django 5.2.5 on 2025-11-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_pedido_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.IntegerField(),
        ),
    ]
