# Generated by Django 5.2.5 on 2025-11-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_producto_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
