# Generated by Django 5.2.5 on 2025-11-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_producto_descuento_porcentaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento_porcentaje',
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.PositiveIntegerField(default=0, help_text='Descuento en %'),
        ),
    ]
