# Generated by Django 5.2.8 on 2025-11-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_pedido_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='actualizado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(null=True),
        ),
    ]
