# Generated by Django 5.2.8 on 2025-11-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_producto_actualizado_alter_producto_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='actualizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
